"""init

Revision ID: fce49d400397
Revises: 
Create Date: 2020-09-11 14:38:35.086132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce49d400397'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False, comment='时间'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='温度'),
    sa.Column('humidity', sa.Float(), nullable=True, comment='湿度'),
    sa.Column('smoke', sa.Float(), nullable=True, comment='烟雾浓度'),
    sa.Column('light', sa.Float(), nullable=True, comment='光照强度'),
    sa.Column('pressure', sa.Float(), nullable=True, comment='大气压强'),
    sa.Column('altitude', sa.Float(), nullable=True, comment='海拔'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temperature_max', sa.Float(), nullable=True, comment='温度报警值'),
    sa.Column('smoke_max', sa.Float(), nullable=True, comment='烟雾报警值'),
    sa.Column('humidity_max', sa.Float(), nullable=True, comment='湿度报警值'),
    sa.Column('air_switch', sa.SmallInteger(), nullable=True, comment='空调开关'),
    sa.Column('air_temperature', sa.Integer(), nullable=True, comment='空调温度'),
    sa.Column('air_model', sa.SmallInteger(), nullable=True, comment='空调模式，0制冷，1制热，2通风'),
    sa.Column('air_wind', sa.SmallInteger(), nullable=True, comment='空调风速，0自动，1弱，2中，3强'),
    sa.Column('air_wind_model', sa.SmallInteger(), nullable=True, comment='0停止，1上下扫风，2左右扫风'),
    sa.Column('lamp_model', sa.SmallInteger(), nullable=True, comment='灯光模式，0关，1弱，2中，3强'),
    sa.Column('curtains_switch', sa.SmallInteger(), nullable=True, comment='窗帘开关'),
    sa.Column('television_switch', sa.SmallInteger(), nullable=True, comment='电视开关'),
    sa.Column('television_chanel', sa.SmallInteger(), nullable=True, comment='电视频道'),
    sa.Column('music_switch', sa.SmallInteger(), nullable=True, comment='音乐开关'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=252), nullable=True, comment='文件名'),
    sa.Column('file_md5', sa.String(length=128), nullable=True, comment='文件md5'),
    sa.Column('file_type', sa.SmallInteger(), nullable=True, comment='文件类型'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column('path', sa.String(length=256), nullable=True, comment='文件路径'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=True, comment='删除标识'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=32), nullable=False, comment='密码'),
    sa.Column('encryption', sa.String(length=6), nullable=False, comment='密文'),
    sa.Column('nickname', sa.String(length=32), nullable=True, comment='昵称'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号码'),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('upload')
    op.drop_table('setting')
    op.drop_table('home')
    # ### end Alembic commands ###
